### ISSUE TITLE
Add special handling for winning Seeker attributes

### ISSUE THREAD

**Issue by stevieraykatz** [coinlander/Coinlander#7]

**Comment by stevieraykatz** [comment]
Winning seeker stats: 
- 100% dank scales
- Max AP
- Uncloaked by default

**Comment by stevieraykatz** [comment]
This is looking close to done. @mikewavsz , can you confirm that the stats added to this guy look good. See method "setWinnerSeekerAttributes" in Seekers.sol. Added here: https://github.com/coinlander/Coinlander/commit/58074ad80cf22b08cb540e445185efe08b6b4eab

**Comment by mikewavsz** [comment]
I like it. God Mode Seeker! What orientation should it be? I'm leaning towards Chaotic Good or Chaotic Neutral because its playstyle will likely be exactly that -- Chaotic. Or, we could have all other attributes (including orientation) be random. Thoughts?

**Comment by stevieraykatz** [comment]
I'm down to randomize! I had true neutral picked because it seemed like the most fitting for an ascended being (like Dr. Manhattan).
